// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NextOccurrence
{
    static class Vsix
    {
        public const string Id = "NextOccurrence.b213c4e9-b96f-4f9d-b1d6-fa8bc7e9da21";
        public const string Name = "Select Next Occurrence";
        public const string Description = @"Selects the next occurrence of the current selection and adds multiple cursors for editing.";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Thomas Welén";
        public const string Tags = "next occurrence, multi selection, ctrl+d";
    }
}
