// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NextOccurrence
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNextOccurrenceCommandsPackageString = "70ceadaa-6e24-4d6d-92aa-6e5a836ca8f2";
        public const string guidNextOccurrenceCommandsPackageCmdSetString = "66543491-5596-4e6c-94d2-bb507832fd49";
        public const string guidImagesString = "e49d8c2f-b246-4f14-b0dd-ca956ca3046a";
        public static Guid guidNextOccurrenceCommandsPackage = new Guid(guidNextOccurrenceCommandsPackageString);
        public static Guid guidNextOccurrenceCommandsPackageCmdSet = new Guid(guidNextOccurrenceCommandsPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SelectNextOccurrenceMenuId = 0x1021;
        public const int SelectNextOccurrenceGroupId = 0x0050;
        public const int SelectNextOccurrenceCommandId = 0x0100;
        public const int SkipOccurrenceCommandId = 0x0110;
        public const int UndoOccurrenceCommandId = 0x0120;
        public const int AddCaretAboveCommandId = 0x0130;
        public const int AddCaretBelowCommandId = 0x0131;
        public const int bmpIcon = 0x0001;
    }
}
